apiVersion: v2
name: tricorder
description: "Helm Charts for Starship, Tricorder Observability's next-generatoin Observability Platform built on eBPF+WASM"

sources:
  - https://github.com/tricorder-observability/helm-charts

maintainers:
  - name: JaredTan95
  - name: yaxiong-zhao

version: 0.1.29

# TODO(yzhao): Let this be propagated as the image tags.
appVersion: "v0.1.0"

dependencies:
  - name: timescaledb-single
    version: 0.27.5
    repository: "https://charts.timescale.com"
    condition: timescaledb-single.enabled
  - name: promscale
    version: 14.6.1
    repository: "https://charts.timescale.com"
    condition: promscale.enabled
  - name: kube-prometheus-stack
    version: 43.2.1
    repository: "https://prometheus-community.github.io/helm-charts"
    condition: kube-prometheus-stack.enabled
