apiVersion: v1
kind: Service
metadata:
  name: api-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: api-server
    app.kubernetes.io/app: starship
spec:
  type: {{ .Values.apiServer.service.type }}
  # TODO(yaxiong): Define mgmt-ui-backend port, and reference it here.
  ports: {{ include "tricorder.svc.ports" . | nindent 4 }}
  selector:
    app.kubernetes.io/name: api-server
