apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tricorder
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tricorder
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tricorder
    spec:
      # Required to get consistent and universal PIDs on the host environment
      hostPID: true
      # Required to get consistent and universal networking metadata on the
      # host environment
      hostNetwork: true
      # Required when hostNetwork is true
      dnsPolicy: ClusterFirstWithHostNet
      volumes:
      - name: lib-modules
        hostPath:
          # Required by BCC to access installed kernel headers
          path: /lib/modules
          type: Directory
      - name: usr-src
        hostPath:
          # /lib/modules/build symlinks to subdirs under /usr/src
          path: /usr/src
          type: Directory
      - name: sys
        hostPath:
          # Required by BCC (usage unclear, need more investigation)
          path: /sys
          type: Directory
      containers:
      - name: agent
        env:
          # Inject outer-scope hostname into container, so the agent can use
          # this to filter out updates not relevant to this node from
          # the K8s API server.
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        image: "{{ .Values.agent.image.repository }}:{{ .Values.agent.image.tag | .Chart.AppVersion }}"
        args:
          - --module_deployer_address=api-server:50051
          - --pg_url=postgresql://postgres:tricorder@timescaledb:5432/tricorder
        imagePullPolicy: Always
        securityContext:
          # Required to deploy eBPF programs.
          privileged: true
        # TODO(yzhao): Add resources
        # resources:
        volumeMounts:
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: usr-src
          mountPath: /usr/src
          readOnly: true
