apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: tricorder-agent
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: tricorder-agent
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: tricorder-agent
  template:
    metadata:
      labels:
        app.kubernetes.io/name: tricorder-agent
    spec:
      # Required to get consistent and universal PIDs on the host environment
      hostPID: true
      volumes:
      - name: lib-modules
        hostPath:
          # Required by BCC to access installed kernel headers
          path: /lib/modules
          type: Directory
      - name: sys
        hostPath:
          # Required by BCC (usage unclear, need more investigation)
          path: /sys
          type: Directory
      containers:
      - name: agent
        env:
          # Inject outer-scope hostname into container, so the agent can use
          # this to filter out updates not relevant to this node from
          # the K8s API server.
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        image: "{{ .Values.agent.image.repository }}:{{ .Values.images.tag | default .Values.agent.image.tag }}"
        args: ["--module_deployer_address=api-server:50051"]
        imagePullPolicy: Always
        securityContext:
          # Required to run eBPF programs
          privileged: true
        # TODO(yzhao): Add resources
        # resources:
        volumeMounts:
        - name: sys
          mountPath: /host/sys
          readOnly: true
        - name: lib-modules
          mountPath: /lib/modules
          readOnly: true
