{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "tricorder.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tricorder.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "tricorder.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups:
  - '*'
  resources:
  - '*' 
  verbs:
  - '*' 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "tricorder.serviceAccountName" . }} 
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "tricorder.serviceAccountName" . }} 
subjects:
- kind: ServiceAccount
  name: {{ include "tricorder.serviceAccountName" . }} 
  namespace: {{ .Release.Namespace }}
{{- end }}
