apiVersion: v1
kind: Service
metadata:
  name: {{ include "tricorder.fullname" . }}-tricorder-ui
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tricorder.labels" . | nindent 4 }}
spec:
  type: {{ .Values.ui.service.type }}
  ports:
    - port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tricorder.selectorLabels" . | nindent 4 }}
