{{- $db := index .Values "timescaledb-single" -}}
{{- if and
    $db.enabled
    (eq .Values.promscale.connectionSecretName "tricorder-promscale-connection")
    (eq .Values.promscale.connection.password "")
    (eq .Values.promscale.connection.uri "")
-}}
---
apiVersion: v1
kind: ServiceAccount
#automountServiceAccountToken is needed to since password-initializer.sh is
#using kubectl to access the Kubernetes api
automountServiceAccountToken: true
metadata:
  name: {{ .Release.Name }}-promscale-initializer-sa
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "tricorder.fullname" . }}
    chart: {{ template "tricorder.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-promscale-initializer-role
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "tricorder.fullname" . }}
    chart: {{ template "tricorder.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-promscale-initializer-rolebinding
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "tricorder.fullname" . }}
    chart: {{ template "tricorder.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ .Release.Name }}-promscale-initializer-role
subjects:
- namespace: {{ .Release.Namespace }}
  kind: ServiceAccount
  name: {{ .Release.Name }}-promscale-initializer-sa
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.promscale.connectionSecretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/resource-policy": keep
  labels:
    app: {{ template "tricorder.fullname" . }}
    chart: {{ template "tricorder.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
stringData:
  PROMSCALE_DB_PORT: "5432"
  PROMSCALE_DB_HOST: "{{ tpl $db.clusterName . }}.{{ .Release.Namespace }}.svc"
  PROMSCALE_DB_NAME: "postgres"
  PROMSCALE_DB_USER: "postgres"
  PROMSCALE_DB_SSL_MODE: "require"
  PROMSCALE_DB_PASSWORD: "PLACEHOLDER"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-connection-initializer
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "tricorder.fullname" . }}
    chart: {{ template "tricorder.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  password-initializer.sh: |
    {{- $.Files.Get "scripts/password-initializer.sh" | nindent 4 }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-connection-secret-{{ .Release.Revision }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "tricorder.fullname" . }}
    chart: {{ template "tricorder.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  template:
    spec:
      containers:
      - name: copier
        image: bitnami/kubectl:latest
        command: [ '/scripts/password-initializer.sh' ]
        env:
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: DB_SECRET_NAME
          value: {{ tpl $db.clusterName . }}-credentials
        - name: PROMSCALE_SECRET_NAME
          value: {{ .Values.promscale.connectionSecretName }}
        volumeMounts:
        - name: promscale-initializer
          mountPath: /scripts
      serviceAccountName: {{ .Release.Name }}-promscale-initializer-sa
      restartPolicy: OnFailure
      volumes:
      - name: promscale-initializer
        configMap:
          name: {{ .Release.Name }}-connection-initializer
          defaultMode: 0755
{{- end -}}
