apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tricorder.fullname" . }}-startship
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tricorder.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "tricorder.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.apiServer.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tricorder.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "tricorder.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.apiServer.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "tricorder.fullname" . }}-api-server
          securityContext:
            {{- toYaml .Values.apiServer.securityContext | nindent 12 }}
          image: "{{ .Values.apiServer.image.repository }}:{{ .Values.apiServer.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.apiServer.image.pullPolicy }}
          args:
            {{- range .Values.apiServer.command.extraArgs }}
            - {{ . }}
            {{- end }}
          ports:
            {{- range $key, $port := .Values.apiServer.ports }}
            {{- if $port.enabled }}
            - name: {{ $key }}
              containerPort: {{ $port.containerPort }}
              protocol: {{ $port.protocol }}
              {{- if and $.isAgent $port.hostPort }}
              hostPort: {{ $port.hostPort }}
              {{- end }}
            {{- end }}
            {{- end }}
          # TODO(jian)
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.apiServer.resources | nindent 12 }}
        - name: {{ include "tricorder.fullname" . }}-mgmt-ui
          securityContext:
            {{- toYaml .Values.ui.securityContext | nindent 12 }}
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            {{- range $key, $port := .Values.ui.ports }}
            {{- if $port.enabled }}
            - name: {{ $key }}
              containerPort: {{ $port.containerPort }}
              protocol: {{ $port.protocol }}
              {{- if and $.isAgent $port.hostPort }}
              hostPort: {{ $port.hostPort }}
              {{- end }}
            {{- end }}
            {{- end }}
          # TODO(jian):
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: http
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
