name: Release Charts

on:
  push:
    branches:
      - main
    tags: ["v*"]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Install Helm
        uses: azure/setup-helm@v3.1
        with:
          version: v3.4.1

      - name: Add dependent repositories
        run: |
          helm repo add timescale 'https://charts.timescale.com'
          helm dep up .

      - name: Run chart-releaser
        uses: helm/chart-releaser-action@v1.4.1
        with:
          charts_dir: .
        env:
          CR_TOKEN: "${{ secrets.ACTIONS_TOKEN }}"
