---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: api-server
    app.kubernetes.io/app: starship
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: api-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: api-server
    app.kubernetes.io/app: starship
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: api-server
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: api-server
    app.kubernetes.io/app: starship
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: api-server
subjects:
- kind: ServiceAccount
  name: api-server
  namespace: {{ .Release.Namespace }}
